name: odontoplusapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  scoped_model: ^1.0.1
#  flutter_statusbarcolor: ^0.2.3
#  flutter_launcher_icons: ^0.7.4
  firebase_core: ^0.4.4 # Recursos básicos
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.0+1
#  firebase_storage: ^3.1.0 # Armazenamento de arquivos
  google_sign_in: ^4.1.4
#  image_picker: ^0.6.0+10
#  intl: ^0.16.1
#  cached_network_image: ^2.0.0
#  date_format: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_header.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_header.png
    - assets/images/dentista.jpg
    - assets/images/dentista2.jpg
    - assets/images/dentista3.png
    - assets/icons/facebook1.png
    - assets/icons/facebook2.png
    - assets/icons/google1.png
    - assets/images/logo_header_app.png
    - assets/images/logo_sitio.png
    - assets/icons/instagram.png
    - assets/icons/twitter.png
    - assets/icons/globo.png
    - assets/icons/servicos.png
    - assets/icons/agendamento.png
    - assets/icons/dados.png
    - assets/icons/historico.png
    - assets/icons/convenios.png
    - assets/icons/contato.png
    - assets/icons/instagram2.png
    - assets/images/avatar.png
    - assets/images/avatar2.png
    - assets/images/avatar3.jfif
    - assets/images/unimed.png
    - assets/images/logo2.png
    - assets/icons/home_drawer.png
    - assets/icons/home.png
    - assets/icons/calendar_drawer.png
    - assets/icons/perfil_drawer.png
    - assets/icons/contatos_drawer.png
    - assets/icons/config_drawer.png
    - assets/images/logo_header2.jpg
    - assets/icons/calendar2.png
    - assets/icons/perfil2.png
    - assets/images/unimed2.png
    - assets/icons/home2.png
    - assets/icons/perfil3.png
    - assets/icons/internet.png
    - assets/images/testes/brick.jpg
    - assets/images/testes/entrepreneur.jpg
    - assets/images/testes/girl.jpg
    - assets/images/testes/man.jpg
    - assets/images/testes/woman.jpg
    - assets/images/image-default.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          weight: 700
    - family: Gibson
      fonts:
        - asset: fonts/Gibson-Regular.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
